# Generated by Django 5.1.4 on 2025-01-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='blog.sity'),
        ),
    ]
