# Generated by Django 5.1.4 on 2025-01-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_age_the_purpose_of_dating_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
