# Generated by Django 5.1.4 on 2025-01-08 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
