# Generated by Django 5.1.4 on 2025-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_created_ad_reaction_created_at_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
